### ISSUE TITLE
The brightness increases when I change the screen.

### ISSUE THREAD

**Issue by civanahmetyasin** [Crozzers/screen_brightness_control#14]
Hi, Im back.

When I change window in windows 10. The brightness is increasing. 
Please, watch the video carefully;
[https://youtu.be/ogMRrw3BED0](https://youtu.be/ogMRrw3BED0
)

And Subscribe to my channel :)

**Comment by Crozzers** [comment]
Is this the order of events as I understand it?

1. You set the brightness via `screen_brightness_control`
2. The program ends
3. You switch windows
4. The brightness suddenly increases

**Comment by civanahmetyasin** [comment]
Yes, it usually happens when I switch to white pages.

**Comment by Crozzers** [comment]
If `screen_brightness_control` has exited and the brightness increases after it has exited then I cannot see how I could fix that.
Could this be due to an auto-brightness feature of windows or of the monitor?
