### ISSUE TITLE
 How to control screen rotate with similar way？

### ISSUE THREAD

**Issue by 123heihuhu** [Crozzers/screen_brightness_control#15]
I want design a hardware to achieve Screen Rotate. It`s easy to make a hardware. But I don`t know upper computer software. Your library was similar to what I think.

**Comment by Crozzers** [comment]
There appears to already be a library to do that called `rotate-screen` by [Danny Burrows](https://github.com/danny-burrows).

Here's a link to the [PyPi page](https://pypi.org/project/rotate-screen/) and heres a [GeeksForGeeks article](https://www.geeksforgeeks.org/build-an-application-for-screen-rotation-using-python/) showing an example of how to use it.

The only issue is that it only supports Windows at the moment. If you want to rotate the screen using Linux then calling `xrandr`  via `subprocess.check_output` is probably your best bet.
Something like `subprocess.check_output(['xrandr', '--output', display_name, '--rotate', angle])`
