### ISSUE TITLE
Apple Thunderbolt Display DDC units out of range

### ISSUE THREAD

**Issue by lazzarello** [Crozzers/screen_brightness_control#17]
Hello! I began working on this same idea earlier today and gave this package a try. My hardware is a bit unusual

* Lenovo Thinkpad P1
* Ubuntu Linux 21.04 + KDE desktop
* Apple Thunderbolt display connected through a Thunderbolt 2 => 3 adapter

Here's the VCP value range for brightness as reported by ddcutil
```
lee@wendy:~$ ddcutil getvcp 0x10
VCP code 0x10 (Brightness                    ): current value = 41662, max value = 65535
```

Here's the current value from this package

```
>>> sbc.list_monitors(method='ddcutil')
['Thunderbolt']
>>> sbc.get_brightness(method='ddcutil')
[41662]  
```

And here's me setting the value to 100 and trying to raise it back to 41662, which fails because (I assume) a module has assumed the range will be 0 - 100. I haven't yet looked at the source to debug.

```
>>> sbc.set_brightness(100, method='ddcutil')
>>> sbc.set_brightness(41662, method='ddcutil')
>>> sbc.get_brightness(method='ddcutil')
[100]   
```

My module has a scale function since 16 bits seems like an absurdly high resolution for LED backlights ;)

I'll checkout your source code. I've also not found anything built into KDE that can present a single brightness slider for this type of display so that might be interesting too.

*update*

Thanks for the well documented modular code! It seems that going directly to the I2C functions throw I/O errors.

```
>>> sbc.linux.I2C.get_brightness()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 489, in get_brightness
    results.append(interface.getvcp(0x10))
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 364, in getvcp
    self.write(I2C.GET_VCP_CMD, vcp_code)
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 305, in write
    return super().write(ba)
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 266, in write
    return os.write(self.device, data)
OSError: [Errno 121] Remote I/O error   
>>> sbc.linux.I2C.get_brightness(display=0)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 489, in get_brightness
    results.append(interface.getvcp(0x10))
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 364, in getvcp
    self.write(I2C.GET_VCP_CMD, vcp_code)
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 305, in write
    return super().write(ba)
  File "/home/lee/.local/lib/python3.9/site-packages/screen_brightness_control/linux.py", line 266, in write
    return os.write(self.device, data)
OSError: [Errno 121] Remote I/O error  
```

**Comment by Crozzers** [comment]
Thank you for raising this issue!

> Here's the VCP value range for brightness as reported by ddcutil
> ```
> lee@wendy:~$ ddcutil getvcp 0x10
> VCP code 0x10 (Brightness                    ): current value = 41662, max value = 65535
> ```
The `DDCUtil` method does not currently pay attention to the max brightness value, and so does not adjust these numbers to be percentages correctly. This should be easy to fix.

> [...] It seems that going directly to the I2C functions throw I/O errors.

I somewhat expected something like this as you mentioned that you have a Thunderbolt display. As mentioned in [the docs](https://crozzers.github.io/screen_brightness_control/extras/Installing%20On%20Linux.html#footnotes) the `I2C` method does not currently support [Monitor Control Command Set over USB](https://www.ddcutil.com/usb) like DDCUtil does.

**Comment by Crozzers** [comment]
I've pushed a commit that should fix the units being out of range for the `DDCUtil` method. If you could give it a try that would be swell!

**Comment by lazzarello** [comment]
Scaling works. Both up and down controls do what I expect! Thanks so much. I found an unrelated bug in the fade function. Imma make a fork and see if I can get it in a reproducible state. My first three tries there have been different error conditions output.
