### ISSUE TITLE
Error from get_brightness()

### ISSUE THREAD

**Issue by kenyg2020** [Crozzers/screen_brightness_control#19]
Hello
I tried to my desktop Monitor(HDMI connection to Desktop PC) using sbc.get_brightness() in IDLE Shell 3.10.6 in windows 10.
I got the follwing message
>>>import screen_brightness_control as sbc
>>>sbc = sbc.get_brightness()
====
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    sbc = sbc.get_brightness()
  File "C:\Users\ken\AppData\Roaming\Python\Python310\site-packages\screen_brightness_control\__init__.py", line 44, in get_brightness
    return __brightness(display=display, method=method, meta_method='get', verbose_error=verbose_error)
  File "C:\Users\ken\AppData\Roaming\Python\Python310\site-packages\screen_brightness_control\__init__.py", line 776, in __brightness
    raise ScreenBrightnessError(msg)
screen_brightness_control.helpers.ScreenBrightnessError: 
	no valid output was received from brightness methods
====
1)Brightness by windows setting changes
2)My Display Monitor shows Generic PnP monitor and uses C:\Windows\system32\drivers\monitor.sys
I have no idea why this error comes out?
Could you give me some idea where I have to check it out?

**Comment by Crozzers** [comment]
Hi there! Could you send me the output of
```
import screen_brightness_control as sbc
sbc.list_monitors_info()
```
You can remove any serial numbers/EDID strings as you wish

**Comment by kenyg2020** [comment]
Hello
>>>print(sbc.list_monitors_info())
[{'name': 'None {e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}', 'model': '{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}', 'serial': '5&626138f&2&UID4357', 'manufacturer': None, 'manufacturer_id': 'ALX', 'edid': '00ffffffffffff0005981000d3c733011e1b0103803c2278ea0aa5a2574fa2280f505421081471cf81c081809500b300d1c001010101023a801871382d40582c4500e00e1100001e000000ff00416e726563736f6e0a20202020000000fd00174c0f631e000a202020202020000000fc00416e726563736f6e0a2020202001f2', 'method': <class 'screen_brightness_control.windows.VCP'>, 'index': 0}]

When I used EDID manager DIsplay ID is ALX0010, Device status is inactive, Genetic PnP monitor in Device description.
Device status is inactive means???? 
EDID Block 0 shows
	Block 0 (EDID Base Block), Bytes 0 - 127,  128  BYTES OF EDID CODE:

		        0   1   2   3   4   5   6   7   8   9   
		000  |  00  FF  FF  FF  FF  FF  FF  00  05  98
		010  |  10  00  D3  C7  33  01  1E  1B  01  03
		020  |  80  3C  22  78  EA  0A  A5  A2  57  4F
		030  |  A2  28  0F  50  54  21  08  14  71  CF
		040  |  81  C0  81  80  95  00  B3  00  D1  C0
		050  |  01  01  01  01  02  3A  80  18  71  38
		060  |  2D  40  58  2C  45  00  E0  0E  11  00
		070  |  00  1E  00  00  00  FF  00  41  6E  72
		080  |  65  63  73  6F  6E  0A  20  20  20  20
		090  |  00  00  00  FD  00  17  4C  0F  63  1E
		100  |  00  0A  20  20  20  20  20  20  00  00
		110  |  00  FC  00  41  6E  72  65  63  73  6F
		120  |  6E  0A  20  20  20  20  01  F2

(8-9)    	ID Manufacture Name : ALX
(10-11)  	ID Product Code     : 0010
(12-15)  	ID Serial Number    : N/A
(16)     	Week of Manufacture : 30
(17)     	Year of Manufacture : 2017

(18)     	EDID Version Number : 1
(19)     	EDID Revision Number: 3
... and more
EDID Block 1 shows

	Block 0 (EDID Base Block), Bytes 0 - 127,  128  BYTES OF EDID CODE:

		        0   1   2   3   4   5   6   7   8   9   
		000  |  00  FF  FF  FF  FF  FF  FF  00  05  98
		010  |  10  00  D3  C7  33  01  1E  1B  01  03
		020  |  80  3C  22  78  EA  0A  A5  A2  57  4F
		030  |  A2  28  0F  50  54  21  08  14  71  CF
		040  |  81  C0  81  80  95  00  B3  00  D1  C0
		050  |  01  01  01  01  02  3A  80  18  71  38
		060  |  2D  40  58  2C  45  00  E0  0E  11  00
		070  |  00  1E  00  00  00  FF  00  41  6E  72
		080  |  65  63  73  6F  6E  0A  20  20  20  20
		090  |  00  00  00  FD  00  17  4C  0F  63  1E
		100  |  00  0A  20  20  20  20  20  20  00  00
		110  |  00  FC  00  41  6E  72  65  63  73  6F
		120  |  6E  0A  20  20  20  20  01  F2

(8-9)    	ID Manufacture Name : ALX
(10-11)  	ID Product Code     : 0010
(12-15)  	ID Serial Number    : N/A
(16)     	Week of Manufacture : 30
(17)     	Year of Manufacture : 2017

(18)     	EDID Version Number : 1
(19)     	EDID Revision Number: 3
--- and more

**Comment by Crozzers** [comment]
I ran your monitor's EDID string through `sbc.helpers.EDID.parse` and it threw up an error when trying to parse your monitor's name. Usually it parses the name from the name descriptor block in the EDID string and infers the model from that name. So in my case it reads `"BenQ GL2450H"` as my monitor's name and splits that up into manufacturer name and model.
However, your monitor's name is just `"Anrecson"` so when it gets to this line:
https://github.com/Crozzers/screen_brightness_control/blob/a50ab405010399512a25fea6828b5d4a75635ae6/screen_brightness_control/helpers.py#L148
It ends up throwing an `IndexError` which would explain why the returned monitor information is so garbled.
I've pushed a commit to the [dev branch](https://github.com/Crozzers/screen_brightness_control/tree/dev) that should fix this parsing error if you wish to try that.

However, I'm not sure why garbled monitor info would cause `get_brightness` to error out because all it really needs is the monitor's index.

Could you send back the output of
```python
import screen_brightness_control as sbc
sbc.get_brightness(verbose_error=True)
```

**Comment by kenyg2020** [comment]
Hello
>>>import screen_brightness_control as sbc
>>>sbc.get_brightness(verbose_error=True)
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    sbc.get_brightness(verbose_error=True)
  File "C:\Users\ken\AppData\Roaming\Python\Python310\site-packages\screen_brightness_control\__init__.py", line 44, in get_brightness
    return __brightness(display=display, method=method, meta_method='get', verbose_error=verbose_error)
  File "C:\Users\ken\AppData\Roaming\Python\Python310\site-packages\screen_brightness_control\__init__.py", line 776, in __brightness
    raise ScreenBrightnessError(msg)
screen_brightness_control.helpers.ScreenBrightnessError: 
	no valid output was received from brightness methods

But It will be [100] for example if it works.
here is interesting thing when I see the EDID data 
(12-15)  	ID Serial Number    : N/A
(72-89)  	Detailed Descriptor #2: Monitor Serial Number
			Monitor Serial Number: Anrecson
(108-125)	Detailed Descriptor #4: Monitor Name
                       Monitor Name: Anrecson
 Do you have any idea?

**Comment by kenyg2020** [comment]
"But It will be [100] for example if it works." means I tried another monitor that worked fine.
max_tries = 100
for i in range(5):
    print(sbc.windows.VCP.get_brightness(max_tries))
    time.sleep(1)
This comes out
[]
[]
[]
[]
[]
I think windows.VCP.get_brightness() works. Anything I have to check?

**Comment by Crozzers** [comment]
> "But It will be [100] for example if it works." means I tried another monitor that worked fine.

Ok that makes sense.

So if your monitor is not responding at all, even with increased attempts, I wonder if the monitor is even being asked.
`windows.VCP.get_brightness` does not use `list_monitors_info` to loop over available displays, it uses `windows.VCP.iter_physical_monitors`, which has it's own process for discovering monitors, filtering duplicates/fakes and ignoring laptop displays. I wonder if perhaps it is this process which causes issues.

I've pushed a commit to the [issue19 branch](https://github.com/Crozzers/screen_brightness_control/tree/issue19) which adds a load of debug print statements to `VCP.iter_physical_monitors`, which should allow us to pinpoint exactly what is going on in that function. Could you install that branch and run the following:
```python
import screen_brightness_control as sbc
sbc.windows.VCP.get_brightness()
```

Thank you for your patience with this

**Comment by kenyg2020** [comment]
I am tryin to test branching VCP.iter_physical_monitors but it's not easy for me. 
anyway I realized my monitor can't support DDC-CI so VCP class has no meaning I suppose. So I tried
sbc.windows.WMI.get_brightness() unfortunately I've got error message like that
  File "E:\User1\VideoWall\pythonProject\venv\lib\site-packages\screen_brightness_control\windows.py", line 274, in get_brightness
    brightness_method = _wmi_init().WmiMonitorBrightness()
  File "E:\User1\VideoWall\pythonProject\venv\lib\site-packages\wmi.py", line 882, in query
    handle_com_error()
  File "E:\User1\VideoWall\pythonProject\venv\lib\site-packages\wmi.py", line 258, in handle_com_error
    raise klass(com_error=err)
wmi.x_wmi: <x_wmi: Unexpected COM Error (-2147217396, 'OLE error 0x8004100c', None, None)>

Is that a right way to use sbc.windows.WMI.get_brightness()?

**Comment by Crozzers** [comment]
You monitor doesn't support DDC-CI? Now that's something I have not seen before. Do you know what model your monitor is or where I could find one?

> Is that a right way to use sbc.windows.WMI.get_brightness()?
Yes, that's correct. The `WMI` class gets brightness for laptop displays generally so it won't work for a desktop display
