### ISSUE TITLE
fade_brightness() fails, but get_brightness() and set_brightness() work fine

### ISSUE THREAD

**Issue by drojf** [Crozzers/screen_brightness_control#5]
### Version Information

I had this issue on master and on the latest pip package, but I also did a git bisect and the first breaking commit is this one: 60fe7bd87c75258e259946fce26f983efc4d5233, so all commits after that one have this problem.

I'm on Windows 10, and my monitor is a Dell S2721Q

----

Hi, I was trying out your library and found that the `fade_brightness` function didn't work, even though the `get_brightness` and `set_brightness` functions both worked fine.

It causes the following exception (in verbose mode):

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 220, in set_brightness
    return method(value, **kwargs)
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\site-packages\screen_brightness_control\windows.py", line 819, in set_brightness
    return __set_and_get_brightness(value, display=display, method=method, meta_method='set', **kwargs)
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\site-packages\screen_brightness_control\windows.py", line 778, in __set_and_get_brightness
    raise Exception(msg)
Exception:
        no valid output was received from brightness methods

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 271, in fade
    set_brightness(val, **kwargs)
  File "C:\Users\drojf\AppData\Local\Programs\Python\Python38\lib\site-packages\screen_brightness_control\__init__.py", line 223, in set_brightness
    raise ScreenBrightnessError from e
screen_brightness_control.ScreenBrightnessError: Cannot set/retrieve brightness level
```

----

I did some digging with the debugger, and found that:
- "no_return" kwarg was set to "True" in `fade()` in `__init__.py` 
- the "no_return" kwarg is passed to `__set_and_get_brightness()` (in `windows.py`)
-  the "no_return" kwarg is then passed to `VCP.set_brightness` in `windows.py` https://github.com/Crozzers/screen_brightness_control/blob/0b37a9a856ca3ef0ddbcf7a58ba40ecca8d562cb/screen_brightness_control/windows.py#L762 (debugger tells me that `VCP.set_brightness` is called here)
- the `VCP.set_brightness` in `windows.py` returns None due to this line and the fact "no_return" is set:  https://github.com/Crozzers/screen_brightness_control/blob/0b37a9a856ca3ef0ddbcf7a58ba40ecca8d562cb/screen_brightness_control/windows.py#L472
- `__set_and_get_brightness()` looks through the list of results (the `output` array), and since they are all None, it treats it as an error (it doesn't return) https://github.com/Crozzers/screen_brightness_control/blob/0b37a9a856ca3ef0ddbcf7a58ba40ecca8d562cb/screen_brightness_control/windows.py#L768-L778

----

I changed `fade()` so that it never sets "no_return" to true, and that seems to fix the issue, although I'm sure you put that in there for good reason. You can see the minimal changes to fix the issue (on my Windows machine at least) here: https://github.com/drojf/screen_brightness_control/commit/177cad6c4a05a763bd6d23bb7ffaac718bad4f19

**Comment by Crozzers** [comment]
Thanks for pointing this out.
That is a bit of an oversight on my part by not writing any unit tests untill now.
The reason I put that there is because whenever the `set_brightness` functions in `windows.py` run they will return the result of `get_brightness` and I thought that it would be wasteful to do that here. Clearly I forgot to test this.

Could you create a pull request of this so I can merge this change to the master branch

**Comment by Crozzers** [comment]
Never mind, figured out how to merge from other repos. Change has been merged to the master branch and I will push out a release shortly

**Comment by Crozzers** [comment]
Update has been released. Thanks for contributing

**Comment by drojf** [comment]
Ah sorry for the late reply. I didn't do a pull request because I was very unsure if my changes were correct or not, but in hindsight I should have just done a pull request, as you could just close or modify the pull request if it was wrong.

I tested the latest 0.6.2 module from pip and it works now, thanks for the quick response

**Comment by Crozzers** [comment]
No problem, happy to help
